
development:
  adapter: postgresql
  database: lesson_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: lesson_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: lesson
  pool: 5
  timeout: 5000
